image : google/cloud-sdk:alpine

stages:
  - build
  - deploy


before_script:
  - echo $KEY > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud config set project adhkar

build:
  stage: build
  script:
    - gcloud builds submit --tag gcr.io/adhkar/adhkar

deploy:
  stage: deploy
  script:
    - gcloud beta run deploy --image gcr.io/adhkar/adhkar


