stages:
  - build
  - deploy

default:
  image : google/cloud-sdk:alpine
  before_script:
    - echo $KEY > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file=/tmp/$CI_PIPELINE_ID.json

build:
  stage: build
  script:
    - gcloud builds submit --tag gcr.io/adhkar/adhkar --project=adhkar

deploy:
  stage: deploy
  script:
    - gcloud run deploy adhkar --image gcr.io/adhkar/adhkar --platform managed --region europe-west1 --project=adhkar


