# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.KEY }}
        project_id: adhkar

    # Build and push image to Google Container Registry
    - name: Build
      run: gcloud builds submit --tag gcr.io/adhkar/adhkar --project=adhkar
    # Deploy image to Cloud Run
    - name: Deploy
      run: gcloud run deploy adhkar --image gcr.io/adhkar/adhkar --platform managed --region europe-west1 --project=adhkar --allow-unauthenticated

          

    
    
